// SPDX-License-Identifier: Apache-2.0
//! `routedctl crd gen`: write the CRD manifests derived from the API types.

use std::path::Path;

use anyhow::Context;
use routed_api::v1alpha1::crds;

/// Render every CRD as YAML, keyed by file name (`routed.io_<plural>.yaml`).
///
/// # Errors
/// If serialisation fails (it does not for these types).
pub fn render() -> anyhow::Result<Vec<(String, String)>> {
    let mut out = Vec::new();
    for crd in crds() {
        let plural = crd.spec.names.plural.clone();
        let mut value = serde_json::to_value(&crd).context("serialising CRD")?;
        strip_unsigned_formats(&mut value);
        let yaml = serde_yaml_ng::to_string(&value).context("serialising CRD")?;
        out.push((
            format!("routed.io_{plural}.yaml"),
            format!("# Generated by `routedctl crd gen`; do not edit.\n{yaml}"),
        ));
    }
    Ok(out)
}

/// Kubernetes only knows `int32` / `int64` integer formats; schemars emits
/// `uint32` / `uint64` for unsigned Rust types, which the API server warns about.
fn strip_unsigned_formats(v: &mut serde_json::Value) {
    match v {
        serde_json::Value::Object(map) => {
            if map
                .get("format")
                .and_then(serde_json::Value::as_str)
                .is_some_and(|f| f.starts_with("uint"))
            {
                map.remove("format");
            }
            for child in map.values_mut() {
                strip_unsigned_formats(child);
            }
        }
        serde_json::Value::Array(items) => items.iter_mut().for_each(strip_unsigned_formats),
        _ => {}
    }
}

/// Write the CRDs into `dir`, returning the files written.
///
/// # Errors
/// On I/O errors.
pub fn write(dir: &Path) -> anyhow::Result<Vec<String>> {
    std::fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
    let mut names = Vec::new();
    for (name, yaml) in render()? {
        std::fs::write(dir.join(&name), yaml).with_context(|| format!("writing {name}"))?;
        names.push(name);
    }
    Ok(names)
}

/// Render `docs/crds.md`: a field reference generated from the CRD schemas.
///
/// # Errors
/// If serialisation fails (it does not for these types).
pub fn render_docs() -> anyhow::Result<String> {
    use std::fmt::Write as _;
    let mut md = String::from(
        "# Custom Resource Definitions\n\n> Generated by `routedctl crd docs` from `crates/api`; do not edit by hand.\n\nAPI group `routed.io`, version `v1alpha1`. All kinds are namespaced.\n",
    );
    for crd in crds() {
        let kind = &crd.spec.names.kind;
        let short = crd
            .spec
            .names
            .short_names
            .clone()
            .unwrap_or_default()
            .join(", ");
        let _ = writeln!(
            md,
            "\n## {kind}\n\nPlural `{}`, short names `{short}`.\n",
            crd.spec.names.plural
        );
        let Some(version) = crd.spec.versions.first() else {
            continue;
        };
        let Some(schema) = version
            .schema
            .as_ref()
            .and_then(|s| s.open_api_v3_schema.as_ref())
        else {
            continue;
        };
        let value = serde_json::to_value(schema).context("schema")?;
        let mut rows = Vec::new();
        if let Some(spec) = value.pointer("/properties/spec") {
            walk_schema(spec, "spec", &mut rows);
        }
        if let Some(status) = value.pointer("/properties/status") {
            walk_schema(status, "status", &mut rows);
        }
        md.push_str("| Field | Type | Description |\n|-------|------|-------------|\n");
        for (path, ty, desc) in rows {
            let _ = writeln!(
                md,
                "| `{path}` | {ty} | {} |",
                desc.replace('|', "\\|").replace('\n', " ")
            );
        }
    }
    Ok(md)
}

fn schema_type(v: &serde_json::Value) -> String {
    let base = v
        .get("type")
        .and_then(serde_json::Value::as_str)
        .unwrap_or("object")
        .to_owned();
    if base == "array" {
        let items = v.get("items").map_or_else(|| "any".into(), schema_type);
        return format!("[]{items}");
    }
    if let Some(e) = v.get("enum").and_then(serde_json::Value::as_array) {
        let opts: Vec<String> = e
            .iter()
            .filter_map(serde_json::Value::as_str)
            .map(|s| format!("`{s}`"))
            .collect();
        return opts.join(" / ");
    }
    if let Some(f) = v.get("format").and_then(serde_json::Value::as_str) {
        return format!("{base} ({f})");
    }
    if base == "object" && v.get("additionalProperties").is_some() {
        return "map".into();
    }
    base
}

fn walk_schema(v: &serde_json::Value, path: &str, rows: &mut Vec<(String, String, String)>) {
    let desc = v
        .get("description")
        .and_then(serde_json::Value::as_str)
        .unwrap_or("")
        .to_owned();
    let ty = schema_type(v);
    if path != "spec" && path != "status" {
        rows.push((path.to_owned(), ty.clone(), desc));
    }
    let props = v.get("properties").and_then(serde_json::Value::as_object);
    if let Some(props) = props {
        let required: Vec<&str> = v
            .get("required")
            .and_then(serde_json::Value::as_array)
            .map(|a| a.iter().filter_map(serde_json::Value::as_str).collect())
            .unwrap_or_default();
        for (name, child) in props {
            let marker = if required.contains(&name.as_str()) {
                ""
            } else {
                "?"
            };
            walk_schema(child, &format!("{path}.{name}{marker}"), rows);
        }
    } else if let Some(items) = v.get("items") {
        if items.get("properties").is_some() {
            walk_schema(items, &format!("{path}[]"), rows);
        }
    }
}
