import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  main: [
    'intro',
    'quickstart',
    'how-routing-works',
    'architecture',
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'crds',
        'decision-api',
        'classifier-http',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      collapsed: false,
      items: [
        'operations',
        'threat-model',
        'performance',
      ],
    },
    {
      type: 'category',
      label: 'Gateway integrations',
      // Autogenerated so a new integration guide needs no sidebar edit.
      items: [{type: 'autogenerated', dirName: 'integration'}],
    },
    {
      type: 'category',
      label: 'Decision records',
      items: [{type: 'autogenerated', dirName: 'adr'}],
    },
    'roadmap',
  ],
};

export default sidebars;
